In [2]:
from sklearn.cluster import DBSCAN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from tqdm import tqdm
import bus

In [35]:
def extract_by_period_df(user_df, min_day, max_day):
    user_df = user_df.loc[:, ["tour_period", "user_id"]]
    user_df["tour_period"] = user_df["tour_period"].apply(lambda x:str(x))
    user_df["tour_period"] = user_df["tour_period"].apply(lambda x:x.split(" ")[0])
    user_df["tour_period"] = user_df["tour_period"].apply(lambda x:int(x))
    user_df = user_df[min_day <= user_df["tour_period"]]
    user_df = user_df[user_df["tour_period"] <= max_day]
    return user_df

In [43]:
start_date = datetime.datetime(2019, 6, 1)
end_date = datetime.datetime(2019, 6, 10)

input_path_list = bus.make_input_path(start_date, end_date)
usage_df = bus.load_tatal_usage_data(input_path_list)

user_df = pd.read_csv("user_list.csv", encoding = "cp949")

# 방문 기간내 관광객 id 추출
min_period = 1
max_period = 3
tourist_df = user_df[user_df["tourist"] == 1]
tourist_df = get_tourist_df(tourist_df, min_period, max_period)
tourist_list = list(tourist_df["user_id"].drop_duplicates())
print(min_period, "~", max_period, "일 동안 방문한 관광객 수:",len(tourist_list))

# 방문 기간내 관광객 사용 기록 추출
tourist_usage_df = usage_df[usage_df["user_id"].isin(tourist_list)]
print(min_period, "~", max_period, "일 동안 방문한 관광객 태그 횟수:",len(tourist_usage_df))

# 정류장 정보 가져오기
station_df = pd.read_csv("station_list.csv", encoding = "cp949")

  
# tourist_usage_df
# cluster_df = pd.read_csv("cluster_list.csv", encoding = "cp949")

# # df = pd.merge(usage_df, user_df, on = "user_id")
# cluster_df[]
# df = pd.merge(usage_df, )

100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:07<00:00,  1.27it/s]

1 ~ 3 일 동안 방문한 관광객 수: 20028
1 ~ 3 일 동안 방문한 관광객 태그 횟수: 113222

In [19]:
usage_df
tourist_df = user_df[user_df["tourist"] == 1]
user_df

,user_id,first_usage_datetime,last_usage_datetime,tour_period,tourist
0,f6f372cf8c6732eafc2a82b4f9d7a08bb3b493213ea4ef...,2019-06-01 15:02:25,2019-06-09 20:47:31,8 days 05:45:06.000000000,1
1,3f6cfe2429f6e8d62cddc39222993405789b7b9ea2a592...,2019-06-01 15:02:29,2019-08-28 18:45:54,88 days 03:43:25.000000000,0
2,107cd874732b48a35df957bf653751154b0234e5573ba5...,2019-06-01 07:20:13,2019-08-28 16:09:42,88 days 08:49:29.000000000,0
3,27b16001fafd812b1e5c474cbc60455a9286ad27ecf8e5...,2019-06-01 07:45:59,2019-08-28 18:32:47,88 days 10:46:48.000000000,0
4,89c9a1c6e5915df4c192acc54067ee9a743f44eb559f3b...,2019-06-01 17:42:06,2019-08-28 19:38:13,88 days 01:56:07.000000000,0
...,...,...,...,...,...
726317,1c0b23153f52f11215e7d1f4e45dcecfa6d669676c4a9f...,2019-08-28 18:30:20,2019-08-28 18:30:20,0 days 00:00:00.000000000,0
726318,8235b6d43ba2e06d89fe94fda0dfdb7b4fe678ac58eaf5...,2019-08-28 18:54:37,2019-08-28 18:54:37,0 days 00:00:00.000000000,0
726319,f6f259fe96fd2e245be452a154c7c43ac747bc0f5d5ad1...,2019-08-29 00:16:52,2019-08-29 00:16:52,0 days 00:00:00.000000000,0
726320,670048e0bb0ed87661ef4e33fe476d74e4616c137bcdb0...,2019-08-29 00:17:12,2019-08-29 00:17:12,0 days 00:00:00.000000000,0
726321,e369089abfaf251ff6fe67c33ca540b642338c76a7e3cb...,2019-08-29 00:10:17,2019-08-29 00:10:17,0 days 00:00:00.000000000,1

In [ ]:
usage_df.to_csv("temp_df.csv", encoding="cp949")

In [5]:
a = tag_df.dropna(axis=0)
a

,user_id,base_date,route_id,route_name,route_no,geton_datetime,geton_station_id,geton_stataion_name,geton_station_longitude,geton_station_latitude,getoff_datetime,getoff_station_id,getoff_station_name,getoff_station_longitude,getoff_station_latitude,user_type,user_count,input_date,tourist
0,f6f372cf8c6732eafc2a82b4f9d7a08bb3b493213ea4ef...,20190601,22610000,292-2(한림체육관~제주버스터미널(종점)),292-2,20190601150225,988,납읍리사무소,126.32944,33.43944,2.019060e+13,26.0,하귀초등학교,126.40212,33.48017,일반,1,20190603,1
1,f6f372cf8c6732eafc2a82b4f9d7a08bb3b493213ea4ef...,20190601,28700000,202-14(구 터미널~제주버스터미널),202-14,20190601152503,26,하귀초등학교,126.40212,33.48017,2.019060e+13,389.0,서문로터리,126.51932,33.51173,일반,1,20190601,1
2,3f6cfe2429f6e8d62cddc39222993405789b7b9ea2a592...,20190601,22610000,292-2(한림체육관~제주버스터미널(종점)),292-2,20190601150229,988,납읍리사무소,126.32944,33.43944,2.019060e+13,26.0,하귀초등학교,126.40212,33.48017,일반,1,20190603,0
3,3f6cfe2429f6e8d62cddc39222993405789b7b9ea2a592...,20190601,23610000,365-21(제주대학교~제주한라대학교(종점)),365-21,20190601201306,3271,제주시청(광양방면),126.53035,33.49892,2.019060e+13,187.0,은남동,126.49248,33.48588,일반,1,20190602,0
5,3f6cfe2429f6e8d62cddc39222993405789b7b9ea2a592...,20190601,23510000,356-1(수산리사무소앞~제주대학교),356-1,20190601155313,26,하귀초등학교,126.40212,33.48017,2.019060e+13,342.0,삼무공원,126.49240,33.48980,일반,1,20190601,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,02b1d9245a36332114146cdbd7acf307d56eaf2a79dbae...,20190829,28180000,3001-2(제주국제공항(신제주방면)~제주국제공항),3001-2,20190829001819,150,제주버스터미널,126.51471,33.50020,2.019083e+13,475.0,한화아파트,126.48308,33.47902,일반,1,20190828,0
48,5349769af16ed3978d92ca42931c53d74ac506a2d3319f...,20190829,28190000,3001-3(제주국제공항(구제주방면)~제주도청 신제주로터리),3001-3,20190829000543,305,용문사거리,126.51005,33.50881,2.019083e+13,479.0,대림2차아파트,126.48835,33.47885,일반,1,20190828,0
49,9b6e974566387c96cc25780717eb50408e64610a5c7934...,20190829,28190000,3001-3(제주국제공항(구제주방면)~제주도청 신제주로터리),3001-3,20190829001020,1355,제주국제공항(신제주방면),126.49275,33.50610,2.019083e+13,4033.0,연동한일시티파크,126.48878,33.49152,일반,1,20190828,1
50,90a4d8db628d6c9796682aaf19c4f500f7c34699b42a00...,20190829,28190000,3001-3(제주국제공항(구제주방면)~제주도청 신제주로터리),3001-3,20190829001018,1355,제주국제공항(신제주방면),126.49275,33.50610,2.019083e+13,4033.0,연동한일시티파크,126.48878,33.49152,일반,1,20190828,1
51,e369089abfaf251ff6fe67c33ca540b642338c76a7e3cb...,20190829,28190000,3001-3(제주국제공항(구제주방면)~제주도청 신제주로터리),3001-3,20190829001017,1355,제주국제공항(신제주방면),126.49275,33.50610,2.019083e+13,4033.0,연동한일시티파크,126.48878,33.49152,일반,1,20190828,1

In [4]:
def analyze_stay_time_per_station(station_df, tag_df):
    station_stay_time_df = station_df[["station_id"]]
    station_stay_time_df["user"] = 0
    station_stay_time_df["time"] = 0
    
    id_list = list(set(tag_df["user_id"]))
    for id in tqdm(id_list):
        user_tag_df = tag_df[tag_df["user_id"] == id]
        for i in user_tag_df.index[:-1]:
            user_tag_df.loc[i, "geton_station_id"]
            
tourist_tag_df = tag_df[tag_df["tourist"] == 1]
citizen_tag_df = tag_df[tag_df["tourist"] == 0]

analyze_stay_time_per_station(station_df, tourist_tag_df.head(1000))

NameError: name 'tag_df' is not defined

In [5]:
station_df

NameError: name 'station_df' is not defined

In [ ]:
def extract_stay_time_by_id(df, id):
    df